import Head from "next/head";
import { useEffect, useState } from "react";



export default function Home() {
  
  
  const [data, setData] = useState([]);
  
  
  const fetchDataFromAPI = async () => {
  const response = await fetch("https://mockend.up.railway.app/api/products");
  const data = await response.json();
  return data;
}


useEffect(() => {
  const data : any = fetchDataFromAPI()
  setData(data);
}, []);


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data.map((item : any) => (
        <div key={item.id}>
          <h1>{item.title}</h1>
          <p>{item.body}</p>
          <button onClick={() => {}}>Add to cart</button>
        </div>
      ))}
    </>
  );
}
